BACKGROUND = 'img/background.png'
BLUEBIRD_MID = 'img/bluebird-midflap.png'
BLUEBIRD_TOP = 'img/bluebird-upflap.png'
BLUEBIRD_BOT = 'img/bluebird-downflap.png'
BASE = 'img/base.png'
CANO = 'img/pipe-red.png'